#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin https://registry.openwms.cloud
docker push registry.openwms.cloud/rebound-registry/org.openwms.common.service.rebound:latest
